version: "3.8"

services:
  openscrapers-postgres:
    image: postgres:17.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dolphins
      # More secure then other passwords: https://github.com/danielmiessler/SecLists/pull/155
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    # ports:
    #   - 5432:5432
  openscrapers-api:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - postgres
    # ports:
    #   - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=openscrapers"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.blog.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    volumes:
      - openpuc_scrapers:/app/openpuc_scrapers
    environment:
      - SQL_DB_CONNECTION=postgresql://postgres:dolphins@openscrapers-postgres:5432/postgres
      - OPENSCRAPERS_S3_ACCESS_KEY=${OPENSCRAPERS_S3_ACCESS_KEY}
      - OPENSCRAPERS_S3_SECRET_KEY=${OPENSCRAPERS_S3_SECRET_KEY}

  reverse-proxy:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.constraints=Label(`traefik.namespace`,`openscrapers`)"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mbright@kessler.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yaml"
    ports:
      - "80:80"
      - "443:443"
      - "8083:8080"
    volumes:
      - "./volumes/letsencrypt:/letsencrypt"
      - "/run/podman/podman.sock:/var/run/docker.sock:ro"
      - "./traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml:ro"
