version: "3.8"

services:
  postgres:
    image: postgres:17.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
  openscrapers-api:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - openpuc_scrapers:/app/openpuc_scrapers
    environment:
      - SQL_DB_CONNECTION=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
