# docker-compose.yml
version: "3.8"

services:
  scraper:
    build: .
    environment:
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}
    volumes:
      - ./outputs:/app/outputs
    command: ["python", "create_scraper_script.py", "--url", "${URL}"]
